"""parts core: categories, technicians, items, movements

Revision ID: cecb0dc654a6
Revises: d01241c741c5
Create Date: 2026-08-10 08:39:26.890388
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cecb0dc654a6'
down_revision: str | None = 'd01241c741c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('legacy_id', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_nome'), ['nome'], unique=False)

    op.create_table('items',
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('saldo_cache', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=False),
    sa.Column('legacy_id', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_nome'), ['nome'], unique=False)

    op.create_table('technicians',
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('legacy_id', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technicians_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technicians_nome'), ['nome'], unique=False)

    op.create_table('movements',
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'AJUSTE_POS', 'AJUSTE_NEG', name='movementtype', native_enum=False, length=16), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Uuid(), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=False),
    sa.Column('detalhes', sa.String(length=500), nullable=False),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('saldo_resultante', sa.Integer(), nullable=False),
    sa.Column('estorno_de', sa.Uuid(), nullable=True),
    sa.Column('legacy_id', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_legacy_id'), ['legacy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movements_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_movements_item_id'))

    op.drop_table('movements')
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technicians_nome'))
        batch_op.drop_index(batch_op.f('ix_technicians_legacy_id'))

    op.drop_table('technicians')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_nome'))
        batch_op.drop_index(batch_op.f('ix_items_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_items_category_id'))

    op.drop_table('items')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_nome'))
        batch_op.drop_index(batch_op.f('ix_categories_legacy_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
